import {useMemo,useState} from 'react';import {useSearchParams} from 'react-router-dom';import {Activity,AlertTriangle,Clock,Search,X} from 'lucide-react';
import {Empty,PageTitle,PilotBadge,Status} from '../components/common';import {FlowCanvas} from '../components/FlowCanvas';import {RolloutPanel} from '../components/RolloutPanel';import {snapshotOf,useAppStore} from '../store/useAppStore';
const filters:[string,string][]=[['all','全部'],['pilot','试点新版'],['rollback','停批回旧'],['abnormal','异常'],['timeout','超时'],['running','进行中'],['completed','已完成']];
export function Monitor(){const ins=useAppStore(s=>s.instances),ws=useAppStore(s=>s.workflows),[params]=useSearchParams();const [filter,setFilter]=useState('all'),[selected,setSelected]=useState<string|null>(params.get('instance'));
 const rows=useMemo(()=>ins.filter(i=>filter==='all'||i.status===filter||i.pilotStatus===filter),[ins,filter]);
 const item=ins.find(i=>i.id===selected),flow=ws.find(w=>w.id===item?.workflowId);
 // 详情按申请提交时锁定的版本渲染（办理中不随后续灰度变化）
 const snap=item&&flow?snapshotOf(flow,item.execVersion):{nodes:flow?.nodes||[],edges:flow?.edges||[]};
 return <div className="page"><PageTitle eyebrow="运行中心" title="Runtime Monitor" desc="按申请查看执行版本与试点状态；主管可在此停批 / 再开放试点域。"/>
 <RolloutPanel/>
 <section className="monitor-kpis">{[['运行中',ins.filter(i=>i.status==='running').length,Activity],['异常',ins.filter(i=>i.status==='abnormal').length,AlertTriangle],['超时',ins.filter(i=>i.status==='timeout').length,Clock],['试点中申请',ins.filter(i=>i.pilotStatus==='pilot').length,Activity]].map(([a,b,I]:any)=><article key={a}><I/><span><small>{a}</small><b>{b}</b></span></article>)}</section>
 <div className="toolbar panel"><div className="search"><Search/><input placeholder="搜索实例或申请人"/></div>{filters.map(([v,l])=><button key={v} className={'filter '+(filter===v?'active':'')} onClick={()=>setFilter(v)}>{l}</button>)}</div>
 <section className="panel monitor-table"><table><thead><tr><th>实例编号</th><th>申请人</th><th>业务域</th><th>当前节点</th><th>执行版本 / 试点</th><th>状态</th><th>提交时间</th><th>耗时</th><th>风险</th></tr></thead><tbody>{rows.map(i=><tr key={i.id} data-testid="instance-row" onClick={()=>setSelected(i.id)}><td><b>{i.id}</b></td><td>{i.applicant}</td><td>{i.domain}</td><td>{i.currentNode}</td><td><PilotBadge status={i.pilotStatus} version={i.execVersion}/></td><td><Status value={i.status}/></td><td>{i.submittedAt}</td><td>{i.duration}</td><td><Status value={i.risk}/></td></tr>)}</tbody></table>{!rows.length&&<Empty title="没有匹配的申请"/>}</section>
 {item&&flow&&<div className="drawer-backdrop"><aside className="instance-drawer" data-testid="instance-detail"><div className="drawer-head"><div><small>流程实例详情</small><h2>{item.id}</h2></div><button className="icon-btn" onClick={()=>setSelected(null)}><X/></button></div><div className="detail-meta"><div><small>申请人</small><b>{item.applicant}</b></div><div><small>业务域</small><b>{item.domain}</b></div><div><small>状态</small><Status value={item.status}/></div><div><small>耗时</small><b>{item.duration}</b></div><div><small>风险</small><Status value={item.risk}/></div><div className="meta-version"><small>执行版本 / 试点（提交时锁定）</small><PilotBadge status={item.pilotStatus} version={item.execVersion}/></div></div><h3>执行流程 · v{item.execVersion}</h3><div className="runtime-canvas"><FlowCanvas nodes={snap.nodes} edges={snap.edges} onNodes={()=>{}} onEdges={()=>{}} onSelect={()=>{}} highlight={snap.nodes.find(n=>n.data.label===item.currentNode)?.id}/></div><h3>执行时间线</h3><div className="timeline" data-testid="execution-timeline">{item.timeline.map(t=><div key={t.title} className={t.status}><i/><span><b>{t.title}</b><small>{t.time}</small></span><Status value={t.status}/></div>)}</div></aside></div>}</div>}
