import {useState} from 'react';import {useNavigate,useParams} from 'react-router-dom';import {ArrowLeft,Paperclip,RotateCcw} from 'lucide-react';import {PilotBadge} from '../components/common';import {ALL_DOMAINS,useAppStore} from '../store/useAppStore';
import type {Instance} from '../types';
export function Preview(){const nav=useNavigate(),{id}=useParams(),w=useAppStore(s=>s.workflows.find(x=>x.id===id))!,plan=useAppStore(s=>s.getPlan(id!)),routeVersion=useAppStore(s=>s.routeVersion),routePilotStatus=useAppStore(s=>s.routePilotStatus),submit=useAppStore(s=>s.submitPreview);
 const [domain,setDomain]=useState(w.domain);const [values,setValues]=useState<Record<string,string>>({});const [submitted,setSubmitted]=useState(false);const [locked,setLocked]=useState<Instance|null>(null);
 const form=w.nodes.find(n=>n.type==='form'),condition=w.nodes.find(n=>n.type==='condition');
 // 预览阶段按业务域当前路由取执行版本；提交后改看申请锁定的版本快照
 const execVersion=locked?.execVersion??routeVersion(id!,domain);
 const pilotStatus=locked?.pilotStatus??routePilotStatus(id!,domain);
 const snap=w.versions.find(v=>v.version===execVersion);const snapCond=snap?.nodes.find(n=>n.type==='condition')??condition;
 const amount=Number(values.amount||0),threshold=Number(snapCond?.data.config.value??5000),branch=amount>threshold?'高额分支：通知财务审批人':'标准分支：写入系统记录';
 const doSubmit=()=>{setSubmitted(true);if((form?.data.config.fields||[]).some((f:any)=>f.required&&!values[f.id]))return;const ins=submit(id!,domain);setLocked(ins)};
 const reset=()=>{setValues({});setSubmitted(false);setLocked(null)};
 const route=plan?.domains.find(d=>d.domain===domain);
 return <div className="preview-page"><header className="preview-header"><button className="icon-btn" onClick={()=>nav(`/workflows/${id}`)}><ArrowLeft/></button><div><b>表单预览</b><small>{w.name} · 按业务域灰度路由</small></div><span className="spacer"/><button className="secondary" onClick={reset}><RotateCcw/>重置</button><button data-testid="preview-submit" onClick={doSubmit}>模拟提交</button></header><div className="preview-stage"><section className="form-preview"><div className="form-cover"><small>{domain} / 申请表单</small><h1>{form?.data.label||'业务申请'}</h1><p>请完整填写以下信息，带 * 的字段为必填项。</p></div>
 <div className="route-card" data-testid="preview-route"><div><small>业务域（新申请路由）</small><select aria-label="业务域" value={domain} disabled={!!locked} onChange={e=>{setDomain(e.target.value);setSubmitted(false)}}>{ALL_DOMAINS.map(d=><option key={d}>{d}</option>)}</select></div><div><small>{locked?'本申请已锁定版本':'该域新申请将执行'}</small><PilotBadge status={pilotStatus} version={execVersion}/></div>{route?.status==='halted'&&!locked&&<p className="route-warn">该试点域已被主管停批，后续申请回 v{plan!.stableVersion} 旧版本，其他试点域照常</p>}{route?.status==='pilot'&&route.reopenVersion!=null&&!locked&&<p className="route-note">该域停批后再开放，主管指定执行 v{route.reopenVersion}</p>}{locked&&<p className="route-ok" data-testid="submit-locked">已生成 {locked.id}，办理期间始终保留 v{locked.execVersion}，不受后续停批 / 再开放影响</p>}</div>
 <div className="form-body">{(form?.data.config.fields||[]).map((f:any)=><label key={f.id}>{f.label}{f.required&&<em>*</em>}{f.type==='attachment'?<div className="upload"><Paperclip/><b>拖入文件或点击上传</b><small>支持 PDF、DOCX、PNG，单个文件不超过 20MB</small></div>:f.type==='text'?<textarea aria-label={f.label} value={values[f.id]||''} onChange={e=>setValues({...values,[f.id]:e.target.value})} rows={5} placeholder="请输入详细说明（最多 2,000 字）"/>:<div className={f.type==='amount'?'money-input':''}>{f.type==='amount'&&<span>¥</span>}<input aria-label={f.label} type={f.type==='amount'||f.type==='number'?'number':f.type==='date'?'date':'text'} value={values[f.id]||''} onChange={e=>setValues({...values,[f.id]:e.target.value})} placeholder={f.type==='amount'?'0.00':'请输入'}/></div>}{submitted&&f.required&&!values[f.id]&&<small className="field-error">此字段为必填项</small>}</label>)}</div></section>
 <aside className="simulation"><h3>条件分支模拟</h3><p>按申请执行版本（v{execVersion}）的规则实时计算流程走向。</p><div className="sim-rule"><small>当前规则 · v{execVersion}</small><b>申请金额 &gt; ¥{threshold.toLocaleString()}</b></div><div className={'sim-result '+(amount>threshold?'high':'normal')} data-testid="branch-result"><small>模拟结果</small><b>{branch}</b><p>当前输入：¥{amount.toLocaleString(undefined,{minimumFractionDigits:2})}</p></div><div className="sim-path"><span className="done">提交申请</span><i>↓</i><span className="done">直属主管审批</span><i>↓</i><span className="active">{amount>threshold?'高额通知':'记录系统'}</span></div></aside></div></div>}
