import type {FlowEdge,FlowNode,RolloutPlan,Workflow} from '../src/types';
const n=(id:string,type:FlowNode['type'],x:number,y:number,label:string,config:Record<string,any>={}):FlowNode=>({id,type,position:{x,y},data:{label,state:Object.keys(config).length?'valid':'unconfigured',config}});
const standard=(broken=false)=>{
 const nodes=[n('start','start',20,150,'开始',{ok:true}),n('form','form',210,150,'提交申请',{fields:[{id:'reason',label:'申请说明',type:'text',required:true},{id:'amount',label:'申请金额',type:'amount',required:true},{id:'attachment',label:'附件',type:'attachment',required:false}]}),n('approval','approval',420,150,'直属主管审批',{approverSource:'直属主管',instruction:'请确认申请内容与预算归属'}),n('condition','condition',630,150,'金额判断',broken?{}:{ruleType:'amount',operator:'>',value:5000}),n('notify','notify',850,40,'高额通知',{targets:'财务审批人',template:'高额申请提醒',timing:'分支进入时'}),n('automation','automation',850,260,'记录系统',{action:'写入系统记录'}),n('end','end',1070,150,'结束',{ok:true})];
 const edges:FlowEdge[]=[['start','form'],['form','approval'],['approval','condition'],['condition','notify','大于 5,000'],['condition','automation','其他'],['notify','end'],['automation','end']].map((e,i)=>({id:'e'+i,source:e[0],target:e[1],label:e[2]})); return {nodes,edges};
};
// 灰度候选 v3：金额阈值上调到 8,000，高额分支通知财务共享中心（与 v2 形成可见差异）
const candidate=()=>{const g=standard(false); const cond=g.nodes.find(x=>x.id==='condition')!,note=g.nodes.find(x=>x.id==='notify')!; cond.data.config={...cond.data.config,value:8000}; note.data.config={...note.data.config,targets:'财务共享中心'}; g.edges=g.edges.map(e=>e.id==='e3'?{...e,label:'大于 8,000'}:e); return g};
const names=['差旅费用审批','采购合同审批','员工入职流程','IT 服务请求','用印申请','供应商准入','年度预算调整','客户退款审批','法务审查流程','资产领用审批','营销活动报备','跨区域大型采购及多部门联合审批流程（集团特别管控版）'];
export const workflows:Workflow[]=names.map((name,i)=>{const graph=i===10?{nodes:[],edges:[]}:standard(i===0||i===3); if(i===8) graph.nodes=graph.nodes.filter(x=>x.type!=='end'); if(i===9) graph.nodes.push(n('orphan','approval',650,390,'孤立审批',{})); const status=i===0?'published':i%4===0?'draft':i%5===0?'archived':'published'; const oldGraph=standard(false); const oldNodes=oldGraph.nodes.filter(x=>x.id!=='notify'); const v3=candidate(); const isWf1=i===0; return {id:'wf-'+(i+1),name,domain:['财务','采购','人力资源','IT服务','法务'][i%5],status,version:isWf1?3:i%3+1,editor:['林秋','陈默','周礼','王宁'][i%4],updatedAt:`2026-07-${String(10-i%9).padStart(2,'0')} ${9+i%8}:20`,publishedAt:status==='published'?'2026-07-09 15:10':undefined,abnormalCount:i===7?0:i%4,nodes:graph.nodes,edges:graph.edges,versions:[{version:1,createdAt:'2026-06-12 10:00',note:'初始化流程结构',nodes:oldNodes,edges:oldGraph.edges.filter(e=>e.source!=='notify'&&e.target!=='notify')},{version:2,createdAt:'2026-07-01 16:20',note:'增加金额分支与通知节点',nodes:oldGraph.nodes,edges:oldGraph.edges},...(isWf1?[{version:3,createdAt:'2026-07-09 15:10',note:'金额阈值调整为 8,000，高额分支改通知财务共享中心（分批试点）',nodes:v3.nodes,edges:v3.edges}]:[])]};});
// wf-1 分批试点计划：财务、IT服务 走新版本 v3；采购发现异常已停批，新申请回 v2；其余域仍现网 v2
export const rolloutPlans:RolloutPlan[]=[{workflowId:'wf-1',candidateVersion:3,stableVersion:2,updatedAt:'2026-07-10 09:40',domains:[{domain:'财务',status:'pilot',updatedAt:'2026-07-09 15:10'},{domain:'IT服务',status:'pilot',updatedAt:'2026-07-09 15:10'},{domain:'采购',status:'halted',updatedAt:'2026-07-10 09:40'},{domain:'人力资源',status:'production',updatedAt:'2026-07-09 15:10'},{domain:'法务',status:'production',updatedAt:'2026-07-09 15:10'}],audits:[{id:'au-1',action:'start-pilot',domain:'财务',time:'2026-07-09 15:10',operator:'林秋',detail:'纳入首批试点，新申请路由到 v3',version:3},{id:'au-2',action:'start-pilot',domain:'IT服务',time:'2026-07-09 15:10',operator:'林秋',detail:'纳入首批试点，新申请路由到 v3',version:3},{id:'au-3',action:'halt-pilot',domain:'采购',time:'2026-07-10 09:40',operator:'陈默',detail:'高额分支通知异常，主管停批，该域新申请回退 v2',version:3}]}];
